services:
  nginx-http:
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/http.conf:/etc/nginx/conf.d/http.conf
      - ./nginx/common:/etc/nginx/common
      - ./nginx/html:/usr/share/nginx
      - ./cert/hoge.crt:/etc/certificates/hoge.crt
      - ./cert/hoge.key:/etc/certificates/hoge.key
      - ./cert/dhparam.pem:/etc/certificates/dhparam.pem
  unit-http:
    image: "unit:php"
    volumes:
      - ./unit/config-http.json:/docker-entrypoint.d/config.json
      - ./nginx/html:/usr/share/nginx

